spring.application.name=discovery-server
server.port=8761

# Discovery server không tự đăng ký chính nó
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL mặc định cho các service khác trỏ tới
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# (khuyên dùng) tắt self-preservation ở local/dev để dễ test
eureka.server.enable-self-preservation=false

# (tuỳ chọn) log gọn hơn khi dev
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
