[build]
  builder = "dockerfile"
  dockerfilePath = "server/Dockerfile"
  watchPatterns = ["server/**"]

[deploy]
  restartPolicyType = "always"
  healthcheckPath = "/actuator/health"
  healthcheckTimeout = 300

[env]
  PGTZ = "UTC"