[build]
  builder = "nixpacks"
  watchPatterns = ["server/**"]

[deploy]
  startCommand = "java -Dserver.port=$PORT -jar target/FruitShop-0.0.1-SNAPSHOT.jar"
  restartPolicyType = "always"
  healthcheckPath = "/actuator/health"
  healthcheckTimeout = 300

[app]
  workingDirectory = "server"
  
[env]
  PGTZ = "UTC"