[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["chmod +x mvnw", "./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.address=0.0.0.0 -Dserver.port=${PORT:-8080} -jar target/FruitShop-0.0.1-SNAPSHOT.jar"
